### ISSUE TITLE
Quality of Life: Create a style guide.

### ISSUE THREAD

**Issue by JulianWebb** [UnofficialNodejsDiscord/Unofficial-Node.js-Discord-Bot#32]
Everyone has a different idea of how code should be stylized, which is great, until there is more than one contributor to a project.

Creating a style guide for the UNDB would put to rest the "formatting" pull requests (at least once all the code fits the standard) that happen every time someone new starts submitting PRs.

It would also be good practise for future projects.

**Comment by mcaustin1** [comment]
All code should adhere to the ESLint style guide which is provided with the bot. The Codacy bot will automatically cull through the repo to find any code that does not adhere to the style guide. As well, pull requests will be automatically notified if they do not match the ESLint style guide. Any pull request which does not follow the ESLint style guide will be asked to change to adhere to it. Failure to do so will result in a denied pull request.
