### ISSUE TITLE
RichEmbed Values May Not Be Empty on messageUpdate.js

### ISSUE THREAD

**Issue by hollowomnicron** [UnofficialNodejsDiscord/Unofficial-Node.js-Discord-Bot#38]
**Describe the bug**
RangeError: RichEmbed field values may not be empty in messageUpdate.js on Line 21
**To Reproduce**

1. Do a Message 
2. Edit it
3. See Unhandled Rejection

**Expected behavior**

No Rejection Should Occur

**Screenshots**
![image](https://user-images.githubusercontent.com/35974849/48091319-58de9300-e1d7-11e8-8be6-1e9d57213179.png)

**Comment by hollowomnicron** [comment]
Further Investigation, it appears this is caused when the Bot lacks the Permission to view the Server Audit Log, therefore, it can't create add the old message

**Comment by mcaustin1** [comment]
Will work on before v2 is released. Seems to be an issue with the bot not checking if it has perms.
